# HTTP Server
server:
   port: 9001

# Logging
logging:
   file: logs/${spring.application.name}.log
   level:
      org.springframework.cloud: 'DEBUG'
      es.microservices: 'INFO'

# Eureka Client
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:1001/eureka/
#   instance:
#      initialStatus: UNKNOWN

# Properties
clock:
   getTime:
      errorEveryNCalls: 10