# HTTP Server
server:
   port: 2001

# Config Server
spring:  
   application:
      name: config-server
   cloud:
      config:
         server:
            native:
               searchLocations: classpath:config/
   profiles:
      active: native

# Logging
logging:
   file: logs/${spring.application.name}.log
   level:
      com.netflix.discovery: 'OFF'
      org.springframework.cloud: 'DEBUG'
      es.microservices: 'INFO'

# Eureka Client
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:1001/eureka/